pretrained_model_path: "/data/a/bowenz/models/text-to-video-ms-1.7b"
output_root: "/data/a/bowenz/generative-models/mavin/unified_model_output/rjes"
cached_latent_dir: "/data/a/bowenz/generative-models/mavin/outputs/cached_latents"
experiment_name: "f16hw384sr2"

train_data:
  video_root:
    - "LAMP/training_videos/horse_run_s2"
    - "LAMP/training_videos/horse_jump_s2"
    - "LAMP/training_videos/horse_eat_s2"
    - "LAMP/training_videos/horse_stand"
  prompt:
    - "horse is running"
    - "horse jumps"
    - "horse is eating grass"
    - "horse is standing"
  width: 384
  height: 384
  use_bucketing: False
  n_sample_frames: 16
  sample_frame_rate: 2
  fps: null
  use_random_frame_rate: False
  tokenizer_max_length: 10  # disabled for now, will not use any padding
  do_flip: True
  random_condition_frame: false

validation_data:
  validate_in_train: True  # set this to false to disable validation during training
  prompt: "rjes"  # default to training prompt if not provided
#  prompt: "a horse is standing"  # default to training prompt if not provided
  width: 384
  height: 384
  num_frames: 16
  num_inference_steps: 50
  guidance_scale: 9.0
  starter_image_path: "/data/a/bowenz/generative-models/mavin/data/quick_test/22.png"
  shared_noise: true
  data_dir: "/data/a/bowenz/generative-models/mavin/data/gs"

learning_rate: 1e-5
train_batch_size: 1
max_train_steps: 30000
checkpointing_steps: 1000
validation_steps: 1000
lr_scheduler: "constant"

seed: 64


trainable_modules: "tempconv+allatt"  # choose from "tempatt", "tempconv", "tempcross", "spacross", "allatt", and "adpt", or specify names
image_conditioning: true
connection_prediction: False

user_model_config:  # additional config of UNet that will add to it or overwrite the default config
  use_adapter: False
  cross_image_condition: True
  use_sc_attention: false

frameinit_kwargs:
  enable: true
  camera_motion: null
  noise_level: 850
  filter_params:
    method: 'gaussian'
    d_s: 0.25
    d_t: 0.25

#inference_only: True
#inference_output_dir: './mavin/inference_outputs/rjes'
resume_from_checkpoint: "/data/a/bowenz/generative-models/mavin/unified_model_output/rjes/2024-04-02_15-41-18_f16hw384sr2_tempconv+allatt/checkpoints/checkpoint-5000"